[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_PUBLIC_SUPABASE_URL = "https://otgewrynnrqmtsyvlzrj.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90Z2V3cnlubnJxbXRzeXZsenJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM0MjM4MTMsImV4cCI6MjA4ODk5OTgxM30.qG7XRTBNuxjvcUMEj5HRM-4RWor-wFYfapmnk5Jo90c"
  NEXT_PUBLIC_TRC20_WALLET = "TQofpQffADyHpv25EBZPcQD7scx8AZV5or"
  NEXT_PUBLIC_TRC20_WALLET_2 = "TH2mdXf9wkddGSpynCTLJcS4CcHSLHSv4E"
  NEXT_PUBLIC_BEP20_WALLET = "0xb47669d0d17b57be5af515bf57e0294c130359b1"
  NEXT_PUBLIC_ERC20_WALLET = "0xb47669d0d17b57be5af515bf57e0294c130359b1"
  NEXT_PUBLIC_TELEGRAM_CHANNEL = "t.me/cnwepro"
  NEXT_PUBLIC_TELEGRAM_USER = "@cnwechatpro"
  NEXT_PUBLIC_CONTACT_EMAIL = "support@cnwepro.com"
  SITE_PASSWORD = "888"


[[plugins]]
  package = "@netlify/plugin-nextjs"
