import { NextResponse } from 'next/server';
import { supabaseAdmin as supabase, createAutoUser } from '@/lib/supabase/admin';
import { checkOrderCreation } from '@/lib/fraud-detection';
import { sendOrderCreatedEmail, logNotification } from '@/lib/email';

export const dynamic = 'force-dynamic';

// POST — Create a new order
export async function POST(request: Request) {
    try {
        // x402 check
        const hasPaymentSignature = request.headers.has('payment-signature');
        const wantsX402 = request.headers.get('x-x402-request') === 'true' || request.headers.get('x-payment-required') === 'true';
        const isAgent = request.headers.get('user-agent')?.toLowerCase().includes('agent') || request.headers.get('user-agent')?.toLowerCase().includes('bot');
        
        if ((wantsX402 || isAgent) && !hasPaymentSignature) {
            const x402Payload = {
                x402Version: 1,
                accepts: [
                    {
                        scheme: "exact",
                        network: "eip155:8453",
                        maxAmountRequired: "5000000", // 5.00 USDC
                        resource: "/api/orders",
                        description: "Create order on CNVerifyHub",
                        payTo: "0x1234567890123456789012345678901234567890",
                        asset: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913",
                        maxTimeoutSeconds: 60
                    }
                ],
                error: "PAYMENT-SIGNATURE header is required"
            };
            const base64Payload = Buffer.from(JSON.stringify(x402Payload)).toString('base64');
            
            return new Response(
                JSON.stringify({ error: "Payment required via x402 protocol", details: x402Payload }),
                {
                    status: 402,
                    headers: {
                        'Content-Type': 'application/json',
                        'payment-required': base64Payload
                    }
                }
            );
        }

        const body = await request.json();
        const { order, items } = body;

        // ── Fraud Detection Check ──
        const totalQuantity = (items as any[]).reduce((sum: number, i: any) => sum + (i.quantity || 0), 0);
        const ip = request.headers.get('cf-connecting-ip') || request.headers.get('x-forwarded-for') || request.headers.get('x-real-ip') || undefined;

        const fraudResult = await checkOrderCreation({
            email: order.email || '',
            ip,
            totalQuantity,
            totalAmount: order.totalAmount || 0,
            isFirstOrder: true, // Conservative default
        });

        if (!fraudResult.allowed) {
            console.warn(`[Fraud] Order BLOCKED: email=${order.email}, severity=${fraudResult.severity}, events=${fraudResult.events.length}`);
            return NextResponse.json(
                { error: 'Order blocked. Please contact support.', fraudSeverity: fraudResult.severity },
                { status: 403 }
            );
        }

        if (fraudResult.events.length > 0) {
            console.log(`[Fraud] Order FLAGGED (allowed): email=${order.email}, severity=${fraudResult.severity}`);
        }

        // ── Auto-Account Creation ──
        let finalUserId = order.userId || null;
        let autoGeneratedPassword = null;

        if (!finalUserId && order.email) {
            const autoUser = await createAutoUser(order.email, order.telegram);
            if (autoUser.userId) {
                finalUserId = autoUser.userId;
                if (autoUser.created) {
                    autoGeneratedPassword = autoUser.tempPassword;
                }
            }
        }

        // Generate a UUID upfront to bypass .select() needing RLS READ permissions
        const generatedOrderId = crypto.randomUUID();

        console.log(`[Orders API] Creating order: public_id=${order.id}, email=${order.email}, amount=${order.totalAmount}, txid=${order.txid || 'none'}`);

        // 1. Insert the main order
        const { error: orderError } = await supabase
            .from('orders')
            .insert({
                id: generatedOrderId,
                public_id: order.id,
                user_id: finalUserId, // Link to auth user (potentially auto-created)
                email: order.email,
                telegram: order.telegram,
                crypto_type: order.cryptoType || 'USDT',
                total_amount: order.totalAmount,
                status: order.status || 'pending',
                txid: order.txid || null, // Save TXID submitted at checkout
                payment_wallet: order.paymentWallet || order.payment_wallet || body.paymentWallet || null,
                payment_network: order.paymentNetwork || order.payment_network || body.paymentNetwork || null
            });

        if (orderError) {
            console.error(`[Orders API] ❌ Supabase Order Error for ${order.id}:`, orderError);
            return NextResponse.json({ error: 'Failed to create order in database' }, { status: 500 });
        }

        // 2. Insert order items
        const orderItems = items.map((item: any) => ({
            order_id: generatedOrderId,
            product_id: item.productId,
            quantity: item.quantity,
            price_at_time: item.priceAtTime || 0
        }));

        const { error: itemsError } = await supabase
            .from('order_items')
            .insert(orderItems);

        if (itemsError) {
            console.error(`[Orders API] ❌ Supabase Items Error for order ${generatedOrderId}:`, itemsError);
            return NextResponse.json({ error: 'Order created but failed to save items' }, { status: 500 });
        }

        console.log(`[Orders API] ✅ Order saved successfully: uuid=${generatedOrderId} (public_id: ${order.id})`);

        // ── Send Order Created Email (fire-and-forget) ──
        if (order.email) {
            sendOrderCreatedEmail({
                to: order.email,
                publicId: order.id,
                totalAmount: order.totalAmount || 0,
                cryptoType: order.cryptoType || 'USDT',
                items: (items as any[]).map((i: any) => ({
                    productId: i.productId,
                    quantity: i.quantity,
                    priceAtTime: i.priceAtTime || 0,
                })),
            }).then(() => {
                logNotification({ orderId: generatedOrderId, type: 'order_created', recipientEmail: order.email });
                console.log(`[Email] ✅ Order created email sent to ${order.email}`);
            }).catch((err: unknown) => {
                console.error('[Email] ❌ Failed to send order created email:', err);
            });
        }

        return NextResponse.json({ 
            success: true, 
            orderId: generatedOrderId, 
            publicId: order.id,
            autoAccount: autoGeneratedPassword ? { email: order.email, password: autoGeneratedPassword } : null
        });
    } catch (error) {
        console.error('[Orders API] ❌ API Order Error:', error);
        return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
    }
}

// GET — Fetch orders (by email or public_id)
export async function GET(request: Request) {
    try {
        // x402 check
        const hasPaymentSignature = request.headers.has('payment-signature');
        const wantsX402 = request.headers.get('x-x402-request') === 'true' || request.headers.get('x-payment-required') === 'true';
        const isAgent = request.headers.get('user-agent')?.toLowerCase().includes('agent') || request.headers.get('user-agent')?.toLowerCase().includes('bot');
        
        if ((wantsX402 || isAgent) && !hasPaymentSignature) {
            const x402Payload = {
                x402Version: 1,
                accepts: [
                    {
                        scheme: "exact",
                        network: "eip155:8453",
                        maxAmountRequired: "100000", // 0.10 USDC to fetch status
                        resource: "/api/orders",
                        description: "Fetch orders on CNVerifyHub",
                        payTo: "0x1234567890123456789012345678901234567890",
                        asset: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913",
                        maxTimeoutSeconds: 60
                    }
                ],
                error: "PAYMENT-SIGNATURE header is required"
            };
            const base64Payload = Buffer.from(JSON.stringify(x402Payload)).toString('base64');
            
            return new Response(
                JSON.stringify({ error: "Payment required via x402 protocol", details: x402Payload }),
                {
                    status: 402,
                    headers: {
                        'Content-Type': 'application/json',
                        'payment-required': base64Payload
                    }
                }
            );
        }

        const { searchParams } = new URL(request.url);
        const email = searchParams.get('email');
        const publicId = searchParams.get('id');
        const status = searchParams.get('status');

        let query = supabase
            .from('orders')
            .select('*, order_items(*)');

        if (publicId) {
            query = query.eq('public_id', publicId);
        } else if (email) {
            query = query.eq('email', email);
        } else {
            return NextResponse.json({ error: 'Email or order ID required' }, { status: 400 });
        }

        if (status) {
            query = query.eq('status', status);
        }

        const { data, error } = await query.order('created_at', { ascending: false }).limit(50);

        if (error) {
            console.error('Fetch Orders Error:', error);
            return NextResponse.json({ error: 'Failed to fetch orders' }, { status: 500 });
        }

        return NextResponse.json({ orders: data || [] });
    } catch (error) {
        console.error('API GET Orders Error:', error);
        return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
    }
}
