import { NextResponse } from 'next/server';
import { supabaseAdmin as supabase, createAutoUser } from '@/lib/supabase/admin';
import { checkOrderCreation } from '@/lib/fraud-detection';

// POST — Create a new order
export async function POST(request: Request) {
    try {
        const body = await request.json();
        const { order, items } = body;

        // ── Fraud Detection Check ──
        const totalQuantity = (items as any[]).reduce((sum: number, i: any) => sum + (i.quantity || 0), 0);
        const ip = request.headers.get('cf-connecting-ip') || request.headers.get('x-forwarded-for') || request.headers.get('x-real-ip') || undefined;

        const fraudResult = await checkOrderCreation({
            email: order.email || '',
            ip,
            totalQuantity,
            totalAmount: order.totalAmount || 0,
            isFirstOrder: true, // Conservative default
        });

        if (!fraudResult.allowed) {
            console.warn(`[Fraud] Order BLOCKED: email=${order.email}, severity=${fraudResult.severity}, events=${fraudResult.events.length}`);
            return NextResponse.json(
                { error: 'Order blocked. Please contact support.', fraudSeverity: fraudResult.severity },
                { status: 403 }
            );
        }

        if (fraudResult.events.length > 0) {
            console.log(`[Fraud] Order FLAGGED (allowed): email=${order.email}, severity=${fraudResult.severity}`);
        }

        // ── Auto-Account Creation ──
        let finalUserId = order.userId || null;
        let autoGeneratedPassword = null;

        if (!finalUserId && order.email) {
            const autoUser = await createAutoUser(order.email, order.telegram);
            if (autoUser.userId) {
                finalUserId = autoUser.userId;
                if (autoUser.created) {
                    autoGeneratedPassword = autoUser.tempPassword;
                }
            }
        }

        // Generate a UUID upfront to bypass .select() needing RLS READ permissions
        const generatedOrderId = crypto.randomUUID();

        // 1. Insert the main order
        const { error: orderError } = await supabase
            .from('orders')
            .insert({
                id: generatedOrderId,
                public_id: order.id,
                user_id: finalUserId, // Link to auth user (potentially auto-created)
                email: order.email,
                telegram: order.telegram,
                crypto_type: order.cryptoType || 'USDT',
                total_amount: order.totalAmount,
                status: 'pending',
                payment_wallet: order.paymentWallet || null,
                payment_network: order.paymentNetwork || null
            });

        if (orderError) {
            console.error('Supabase Order Error:', orderError);
            return NextResponse.json({ error: 'Failed to create order in database' }, { status: 500 });
        }

        // 2. Insert order items
        const orderItems = items.map((item: any) => ({
            order_id: generatedOrderId,
            product_id: item.productId,
            quantity: item.quantity,
            price_at_time: item.priceAtTime || 0
        }));

        const { error: itemsError } = await supabase
            .from('order_items')
            .insert(orderItems);

        if (itemsError) {
            console.error('Supabase Items Error:', itemsError);
            return NextResponse.json({ error: 'Order created but failed to save items' }, { status: 500 });
        }

        return NextResponse.json({ 
            success: true, 
            orderId: generatedOrderId, 
            publicId: order.id,
            autoAccount: autoGeneratedPassword ? { email: order.email, password: autoGeneratedPassword } : null
        });
    } catch (error) {
        console.error('API Order Error:', error);
        return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
    }
}

// GET — Fetch orders (by email or public_id)
export async function GET(request: Request) {
    try {
        const { searchParams } = new URL(request.url);
        const email = searchParams.get('email');
        const publicId = searchParams.get('id');
        const status = searchParams.get('status');

        let query = supabase
            .from('orders')
            .select('*, order_items(*)');

        if (publicId) {
            query = query.eq('public_id', publicId);
        } else if (email) {
            query = query.eq('email', email);
        } else {
            return NextResponse.json({ error: 'Email or order ID required' }, { status: 400 });
        }

        if (status) {
            query = query.eq('status', status);
        }

        const { data, error } = await query.order('created_at', { ascending: false }).limit(50);

        if (error) {
            console.error('Fetch Orders Error:', error);
            return NextResponse.json({ error: 'Failed to fetch orders' }, { status: 500 });
        }

        return NextResponse.json({ orders: data || [] });
    } catch (error) {
        console.error('API GET Orders Error:', error);
        return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
    }
}
